- lib/sonatype-nexus3-stack.ts
- package-lock.json
- package.json
> chore: upgrade aws-cdk to 1.60.0 and lodash to 4.17.19+.

- lib/sonatype-nexus3-stack.ts
- package-lock.json
- package.json
> chore: update cdk to 1.74.0

- .github/workflows/lambda-integration-test.yml
> chore: suppress running duplicated integration test for PRs

- README.md
- bin/sonatype-nexus3.ts
- lib/sonatype-nexus3-stack.ts
- package.json
- test/sonatype-nexus3.test.ts
> feat: across multiple regions support in cloudformation

- lib/sonatype-nexus3-stack.ts
- package-lock.json
- package.json
> chore: add stack description

- lib/sonatype-nexus3-stack.ts
> fix: fix incorrect default value of hosted zone parameter

- .github/workflows/lambda-integration-test.yml
- lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
> chore: update oteemo chart to 4.1.1 and nexus3 to 3.27.0-03

- lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
> feat: encrypt s3 bucket and efs filesystem

- README.md
- lambda.d/nexuspreconfigure/index.py
- lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
- tsconfig.json
> feat: required admin init password when deploying solution

- lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
> chore: bump aws load balancer controller to v2.1.0

- lambda.d/nexus3-purge/index.py
> fix: improve stability of deleting nexus3 resources in custom resource

- README.md
- lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
> feat: deploy with internal ALB not exposing the Nexus OSS to internet

- lib/sonatype-nexus3-stack.ts
- package-lock.json
- package.json
- test/sonatype-nexus3.test.ts
> chore: bump mainline version to 1.1.0 and cdk to 1.80.0

- lib/sonatype-nexus3-stack.ts
> fix: the regex pattern to verify the init password

- package.json
> chore: bump version to v1.0.1

- lib/sonatype-nexus3-stack.ts
> fix: merge hotfix v1.0.1 to mainline

- README.md
> docs: add cloudformation deployment links to global regions

- lib/sonatype-nexus3-stack.ts
- package-lock.json
- package.json
> chore(deps): bump cdk to 1.104.0

- README.md
> docs: make corresponding updates for using projen

- src/lib/sonatype-nexus3-stack.ts
> feat: provision ssm agent as daemonset

- README.md
- src/lib/sonatype-nexus3-stack.ts
- src/sonatype-nexus3.ts
- test/sonatype-nexus3.test.ts
- create new vpc by default
closes #46 
> feat: support reuse existing vpc

- README.md
- src/lambda.d/nexuspreconfigure/index.py
- src/lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
closes #7 
- deploy Nexus Repository OSS to existing EKS cluster
- doc update
- fix purging bug
> feat: support existing EKS cluster

- .github/workflows/lambda-integration-test.yml
> ci: update the trigger of integ test

- src/lib/sonatype-nexus3-stack.ts
> chore: bump efs-csi-driver to 1.3.1

- src/lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
> fix: validation error when deploying EKS with v1.19.

- .projenrc.js
- README.md
- package.json
> docs: update doc for deployment links

- .github/workflows/lambda-integration-test.yml
> ci: update trigger of integ test

- src/lib/sonatype-nexus3-stack.ts
> chore: configure access log of blobstore bucket

- src/lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
> chore: configure access log of ALB created by Nexus helm chart

- .projen/deps.json
- .projen/tasks.json
- .projenrc.js
- package.json
- src/lib/sonatype-nexus3-stack.ts
> chore: enable eks's control plane logs

- src/lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
> chore: make endpoint of cluster private only

- src/lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
> chore: customize ebs encrpytion/ec2 detail monitor by launch template

- .github/workflows/bandit-check.yml
- src/lambda.d/nexus3-purge/index.py
> ci: enable python code scan by bandit

- .cfn-nag-ignore-lists.yml
- .github/workflows/cfn-nag.yml
- src/lib/sonatype-nexus3-stack.ts
- test/sonatype-nexus3.test.ts
> ci: add cfn-nag check as workflow

- src/lib/sonatype-nexus3-stack.ts
> feat: add EKS 1.21 support
